### PR TITLE
Simple arrival vault.  With Lava.  Everyone loves lava.

### PR DESCRIPTION
**Pull request by orjb1**
https://www.reddit.com/r/dcss/comments/14p6u5d/contributing_vaults_an_image_to_glyphs_translaton/

^ testing out this workflow. feel free to reject my unimaginative shit!

### CODE REVIEW

**Comment by mainiacjoe** [comment]
Thanks for giving this a try! I'd love to hear how it went, but this isn't the place for that conversation. Pls DM me at Reddit or comment on the Reddit thread.

**Comment by ebering** [comment]
This is a great first vault! I'm doing a round of merging today so it will get merged soon. Big thanks to maniacjoe for writing the guide.

**Comment by ebering** [comment]
Oh, how would you like to appear in the CREDITS.txt?

**Comment by orjb1** [comment]
Thankee, don't worry about credits until I've done something actively useful!  

I have some more ideas now but need to figure out what's already been done!

**Comment by mainiacjoe** [comment]
Thanks too to orjb1 for feedback on the guide that made it better (though
I've not actually made the edits yet LOL).

I would encourage you to go ahead and get your name on the Contributors
list.  Even if this one vault is the only thing you do, you've still added
to Crawl.

**Comment by orjb1** [comment]
In which case, yes please to the contributors.

**Comment by PleasingFungus** [comment]
Thanks for the contribution! Apologies for the delay.

**Pull request closed without merging**
