### PR TITLE
Slime monster tweaks

### PR DESCRIPTION
**Pull request by PleasingFungus**
Add two new monster types to Slime, remove death oozes, and clean up monster distribution a little bit.

Rockslimes are trampling slimes (credit to hatsuma for this idea) made of rock, so high AC, rF++ and rElec. They're intended to be somewhere near azure jellies in threat level.

Quicksilver oozes are fast-moving slimes with AF_ENGULF and AF_ANTIMAGIC, high EV, and WILL_INVULN. They're supposed to be a bit below azure jellies in threat level.

The goal is to play with new Slime mechanics and somewhat weaken TRJ-?immo tactics while still keeping Slime as a viable third rune. If these new monsters or removal of chaff make Slime too hard, I'll dial them back a few notches.

TODOs:
- Get some sprites.
- More testing.
- Maybe cut qs jelly antimagic, if it confuses people by not being AF_CANCEL? (Or rename/retheme them to be less quicksilvery?)

### CODE REVIEW

**Comment by 21Dani21** [comment]
Have to say I disagree with these changes(signed up just to comment this).  Slime is typically not the 3rd rune at the moment, because its already dangerous, even with immo cheesing.

You want to add elephant style charging WITH acid slimes, which are already extremely dangerous  even with rCorr; (not to mention golden eyes)

You are making this a rune people do after they have already won the game essentially.  Why would you ever come here needing mr+++ for golden eyes, plan to get mutated, need rCorr and mobility for being shoved around while acid jellies pelt you.

Its great to make slime more interesting, but the levels are small, the loot is worse than elf (which doesn't even have a rune), and elf is *already* easier.

If you're adding these quite interesting and dangerous mobs; need to consider increasing rCorr resistance or lowering Acid slime range.  Make the floors bigger/more open.  Add some interesting mini vaults to make the floors worth exploring.    

Your proposed changes 100% make slime a skip for sure for 3rd.

**Comment by PleasingFungus** [comment]
Thanks for the feedback! I appreciate you taking the effort to sign up to post this.

> You are making this a rune people do after they have already won the game essentially. Why would you ever come here needing mr+++ for golden eyes, plan to get mutated, need rCorr and mobility for being shoved around while acid jellies pelt you.

Almost everything you describe there is true now. The only difference is that there are trampling monsters added into the mix. Is that really a big difference?

> You want to add elephant style charging WITH acid slimes, which are already extremely dangerous even with rCorr; (not to mention golden eyes)

I don't understand the connection between rockslime and acid blobs. Can you explain?

> Its great to make slime more interesting, but the levels are small, the loot is worse than elf (which doesn't even have a rune), and elf is already easier.

Sorry, I don't understand why we're referencing Elf here. Elf is of course much easier than Slime - it's reasonable to do before Vaults:1-4. And, as you say, it has no rune. Surely Vaults:5 is a better comparison?

> If you're adding these quite interesting and dangerous mobs; need to consider increasing rCorr resistance or lowering Acid slime range. Make the floors bigger/more open. Add some interesting mini vaults to make the floors worth exploring.

None of these proposed changes have anything to do with what I've added here, and many of them (e.g. making the floors bigger & more open) would tend to make the area more dangerous. Can you explain to me what the connection is?

Thanks again!
-- PF

**Comment by 21Dani21** [comment]
> 
> 
> Thanks for the feedback! I appreciate you taking the effort to sign up to post this.
> 
> > You are making this a rune people do after they have already won the game essentially. Why would you ever come here needing mr+++ for golden eyes, plan to get mutated, need rCorr and mobility for being shoved around while acid jellies pelt you.
> 
> Almost everything you describe there is true now. The only difference is that there are trampling monsters added into the mix. Is that really a big difference?
> 
> > You want to add elephant style charging WITH acid slimes, which are already extremely dangerous even with rCorr; (not to mention golden eyes)
> 
> I don't understand the connection between rockslime and acid blobs. Can you explain?

Acid jellies are *extremely* dangerous for all players, especially /no ranged.  rCorr barely prevents -ac; meaning, when you're getting trampled around with these high AC monsters, the acid jellies are pelting you from a distance.  Stair hopping is usually the solution to drop -ac, now, it will often be /move 2 squares and hope you don't get shoved to get back to stairs (unless they are slippery!)

> 
> > Its great to make slime more interesting, but the levels are small, the loot is worse than elf (which doesn't even have a rune), and elf is already easier.
> 
> Sorry, I don't understand why we're referencing Elf here. Elf is of course much easier than Slime - it's reasonable to do before Vaults:1-4. And, as you say, it has no rune. Surely Vaults:5 is a better comparison?

Slime is already more dangerous than Vaults 5.  I was referring to V5 (the rune)
> 
> > If you're adding these quite interesting and dangerous mobs; need to consider increasing rCorr resistance or lowering Acid slime range. Make the floors bigger/more open. Add some interesting mini vaults to make the floors worth exploring.
> 
> None of these proposed changes have anything to do with what I've added here, and many of them (e.g. making the floors bigger & more open) would tend to make the area more dangerous. Can you explain to me what the connection is?

You are proposing adding mobs that stair shove, _engulf  preventing dances,  antimagic drain mana, all while confusion smiting & acid is likely, stacking up.  The levels are tiny, your /teleport yolo will (now) often just put you back in the same room/vision. 
> 
> Thanks again!
> -- PF

Yes. I know I'm 'emphasizing' scenarios.  But they *will* happen; and, why would you come here and risk the above?  Hit V5, hit elf or even run and do a demonic rune.  Vaults is already done more than slime.

I really like your mobs, I feel that slimes as a whole need to be changed/more interesting.  Maybe Acid jellies range down to 3-4, make rCorr reduce the 'debuff stack' from -4 to -2.  I don't know about the levels;; shorten it to 2-3 floors?  Have one *big* floor with TRJ in a vault in a corner?  Make floors more open with /mini vaults with loot? 

If we just add your mobs as is, slimes will be more exciting.  It will just be a 5-6th rune.

Also, make jellies immune to immolation *the gelatinous blob extinguishes the inner fire*

**Comment by PleasingFungus** [comment]
> Stair hopping is usually the solution to drop -ac, now, it will often be /move 2 squares and hope you don't get shoved to get back to stairs (unless they are slippery!)

It's true that these rockslimes should encourage new tactics! Please keep in mind, though, that I've also reduced the total number of enemies in Slime, and that rockslimes dilute the number of acid blobs further. It's not like I'm just piling these monsters on top of the existing ones!

I appreciate your concerns, and I'm happy to make adjustments based on player experience. We'll see how it goes!

**Pull request merged**
