### PR TITLE
Add 2 alternative suggestions for tiles for #1387

### PR DESCRIPTION
**Pull request by amcnicky**
hood of the Assassin - made sharper, more like a hood, and shifted
colour palette towards red.

Cigotuvi's embrace - proposed a more literal tile, with skulls/heads and
more flesh-like palette.

### CODE REVIEW

**Comment by amcnicky** [comment]
urand_hood_assassin

urand_cigotuvi

**Comment by amcnicky** [comment]
@rawlins Happy to modify based on any feedback you might have, of course.

**Comment by canofworms** [comment]
The assassin hood tile is fine, although it should have an associated doll tile that matches it (the graphic used on the player character tile). The Cigotuvi tile is too low quality to be usable and I'll likely end up making one myself instead.

To summarize, if you add a doll tile for the hood and remove your Cigotuvi tile this will be good to be merged!

**Comment by amcnicky** [comment]
Please accept my sincere apologies for the delay between raising this PR and completing it. Life got a bit tricky for a while there. I do now expect to be in a position to at the very least complete my outstanding patches (starting with this one, the smallest), and then moving onto the two uniques.

Anyway, as requested I've added a doll tile for the assassin's hood, and have replaced my Cigotuvi tile with the current master branch version. Not sure if this was the most efficient way to complete this from a git perspective, but from local testing, this patch plays as expected for both items (assassin's hood updated, cigotuvi tile unchanged).

urand_hood_assassin
urand_cigotuvi
hood_assassin

**Comment by ebering** [comment]
Sometimes things move slow in crawl land. Merged this, finally! Sorry it languished once you made the requested updates.

**Pull request closed without merging**
