### PR TITLE
Panlord tweaks

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Mess around with AC/EV, rF/rC immunity, and rElec levels

### CODE REVIEW

**Comment by drke2** [comment]
:+1:

**Comment by MarvinPA** [comment]
I don't think elec vulnerability should be used here (or really anywhere especially).

**Comment by alexjurkiewicz** [comment]
What's the diff for you between elec vuln and fire/cold vuln?

**Comment by alexjurkiewicz** [comment]
I've significantly added to this commit since @drke2's thumbs up so it may no longer apply. Comments welcome.

Overall this is a pretty significant buff to pan lords, I think. I tried to keep their "personality" -- it's still possible to find the occasional pan lord with terrible defenses and summon butterflies, just less likely.

**Comment by alexjurkiewicz** [comment]
As per IRC, I'm not sure if 9e24628 is a good idea. It might be a better idea to a) remove low level hexes from pan lords (this would remove almost all hexes though) or b) make monster hexes less resistable in general (so that reaching 0/1% success chance against the player isn't a thing that happens)

**Pull request merged**
