### PR TITLE
Only count connected branches for Gozag service fee

### PR DESCRIPTION
**Pull request by alexjurkiewicz**

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Why.

**Comment by alexjurkiewicz** [comment]
Abyss wandering inflates gozag's service fee by counting every piece of
gold generated. Same with Pan (although there at least every piece of gold
could be collected).

**Comment by PleasingFungus** [comment]
Feels like most portal vaults should still count, though.

**Comment by alexjurkiewicz** [comment]
I don't disagree, but it felt like special cases on special cases. If you'd like, I can restrict this to only ignore the Abyss?

**Comment by PleasingFungus** [comment]
Sure, that works for me.

**Comment by alexjurkiewicz** [comment]
Here we go

**Pull request closed without merging**
