### PR TITLE
Convert sixteen more enums to enum classes

### PR DESCRIPTION
**Pull request by NormalPerson7**
Continuing on from #927 and #938, convert sixteen more enums to enum classes, changing some of their names and also three file names, for the enums that have their own file. (The enums changed don't really have a pattern this time.)

I have no specific things to do before this is merged, although I would recommend this be tested first. Note that for all twenty-two enums I have so far converted, I have avoided anything touching tags.cc or anything that has the potential to affect tiles, so as to avoid save compatibility problems.

I have rebased on top of master so there are no merge conflicts at the current time, and I have also checked for whitespace and brace errors. The result should compile.

Please feel free to suggest alternative names for the new enum classes that you feel would be better than the ones I have given.

Let me know if you'd prefer I put more/less of these changes in one PR, and if you'd rather each change be its own commit or if you'd rather they be grouped together for some of the smaller enums.

### CODE REVIEW

**Comment by NormalPerson7** [comment]
Oops I forgot an enum, now it's sixteen :P

**Comment by ebering** [comment]
I'll do a further review later; but after the previous one landed we decided that having markdown in commit messages is not desired, the straight variable name is fine.

**Comment by NormalPerson7** [comment]
Ah so you'd rather not have backticks? That's fine by me, I'll update them when I have a chance.

**Comment by ebering** [comment]
Well, talking on IRC there's not consensus, save your time for more important things for now.

**Comment by rawlins** [comment]
> Well, talking on IRC there's not consensus, save your time for more important things for now.

After talking to gammafunk, the issue specifically is that the git/discord bot has a bug where markdown (or maybe backticks specifically?) in a commit title breaks the messages the bot prints on discord. So not necessarily something to compromise commit message quality on, since a message on discord is a bit ephemeral, but I guess avoiding backticks where not crucial won't hurt.

**Pull request closed without merging**
