### PR TITLE
Give vampire knights and Jory their own weapon list (Roarke)

### PR DESCRIPTION
**Pull request by drke2**
Bladed weapons only - 50% long blades, 33% axes, 17% polearms. Jory gets
a guaranteed good item.

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Why?

**Comment by Huaschei** [comment]
Jory is one of the only mid-game uniques without his own weapon list. 
Similar to Margery and hell knights, this will give him a list similar to the
monster type he is based on.

**Comment by PleasingFungus** [comment]
@Huaschei A unique having 'their own weapon list' is not particularly exciting or interesting in itself. Think of it from a player's perspective - would any reasonable player notice or care about this?

**Comment by alexjurkiewicz** [comment]
I would! It is bad lootfeel (sorry) to kill a unique and "merely" get xp as
a reward. Blue items are a tangible reward unlike xp.

**Comment by PleasingFungus** [comment]
Giving out good items for killing uniques, which i generally support, is orthogonal to unique weapon lists.

**Comment by alexjurkiewicz** [comment]
Oh, I didn't realise we were only talking about weapon list. I agree then,
I don't mind what weapons Jory has, just that they're blue!

In fact for uniques I prefer a smaller set of base types for
distinctiveness.

**Comment by Huaschei** [comment]
The weapon list more closely matches Vampire weapon aptitudes, for flavor. It is also smaller, limited to stronger weapons types to increase the impact of good_item on Jory.

**Comment by drke2** [comment]
PF: It's not orthogonal if the orc weapon list makes him drop an obsolete base type and the unique weapon list would not?

**Comment by drke2** [comment]
Simplifying this. Leave vampire knights alone, give Jory a small list of weapons with good_item as chequers suggested.

**Comment by PleasingFungus** [comment]
SGTM.

**Pull request merged**
