### PR TITLE
Standardize Linux packages

### LINKED ISSUE #1256: Provide an AppImage
[AppImages](https://appimage.org/) are an approach to multi-distro distribution that puts the control in the hands of the developer (as opposed to demi-centralized approaches like flatpak and snapd).
Since Crawl uses Travis CI, the cost of creating an AppImage is relatively low (there is a semi-official [method](https://docs.appimage.org/packaging-guide/travis.html) to generate them inside of Travis).
This would allow users to have a more authentic experience (bypassing distribution maintainers) and remain up to date (assuming publication is automated and update data is embedded as per specification).
This would also simplify the downloads page for linux.

For an example of a high-quality AppImage producer, please take a look at [KeepassXC](https://github.com/keepassxreboot/keepassxc/), though they do not utilize Travis to generate theirs.
The UX of using their official AppImage is great, however.

### PR DESCRIPTION
**Pull request by robertxgray**
Modern Linux distributions and other OSs following the XDG specifications, require some files to integrate programs into desktop menus and software centers. We provide some of these files in the Debian packages (which are uncomplete and outdated), but they cannot be easily reused by other distributions. This leads to every distribution providing their own versions of the files, all of them different. PR #464 tries to address this problem, but it doesn't allow executable name customization via GAME variable (introduced later), it doesn't improve the Debian packages and adds more redundant files to the repository. To make things even worse, I proposed the inclusion of yet another version of these files in #2049.

I made some changes in #464, trying to be flexible enough for every distribution and updated the Debian packages. The AppImage support only requires a few more lines in the Makefile. The name of the files is governed by the GAME variable, so several builds of the game (usually console and tiles) can coexist indepently and without conflicts.

Example:
`make -j4 prefix=/usr DESTDIR=/package/dir TILES=y GAME=crawl-tiles install install-xdg-data`

Detail of changes:

- New build target: install-xdg-data. Installs some files required by Linux packages according to the XDG specifications (freedesktop.org).
  Related resources stored in crawl-ref/source/xdg-data

- New build target: appimage. Builds a Linux AppImage with the help of the install-xdg-data target and the linuxdeploy tool.
    
- Debian build updated to make use of the install-xdg-data target.
  Common files have been removed from the debian folder.
  Fixed missing icon in crawl menu item if crawl-tiles is not installed.
  Use Debian's uses machine-readable format for copyright file.
  Remove menu files based on CTTE #741573.
  
- Documentation and man page updated.

Some test packages are available here:
https://github.com/robertxgray/crawl/releases/tag/linux-1

Refs:
- https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
- https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
- https://wiki.debian.org/AppStream/Guidelines
- https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
- https://lintian.debian.org/tags/command-in-menu-file-and-desktop-file
 
Closes #464
Closes #1256
Closes #2049

### CODE REVIEW

**Comment by robertxgray** [comment]
I have configured GitHub Actions to include AppImage packages in every release.
Sample test here: https://github.com/robertxgray/crawl/releases/tag/0.0.0

**Comment by rawlins** [comment]
Would be great if we can merge this before 0.28 and stop the chain of linux infrastructure PRs languishing, so I've set that as a milestone. I don't suppose there is a team member who uses linux who could look at it though?

**Comment by moozaad** [comment]
Registering my interest on this thread. I'm doing the updates to opensuse packages (very late I know). We're still using @Mailaender's patches from #464 . Can this please be merged for 0.29 as it missed the 0.28 milestone?

**Comment by robertxgray** [comment]
@moozaad I forgot about the AppImages. Could you please also test them on OpenSUSE? Thank you in advance.

**Comment by moozaad** [comment]
@robertxgray the appimages here? https://github.com/robertxgray/crawl/releases

I should be able to get to this early next week, leave it with me.

**Comment by robertxgray** [comment]
@moozaad  Yes, thank you. This PR includes automatic AppImages with every release, but I'm probably the only person who has ever tested them.

I'm having a look at the OpenSUSE resources for building Crawl. You should be able to get rid of the appdata, desktop and icon patches. Then you need at least these changes in the spec file.

1. Add the GAME variable to every `make` command. Assuming you want to preserve the current names:

    - GAME=crawl (console)
    - GAME=crawl-sdl (tiles)
 
This obsoletes the steps where the executables are being renamed.
 
2. Run `make install-xdg-data`. It can be combined with `make install`, don't forget the GAME variable. This will create the following resources.

Console
    `%{_prefix}/share/applications/org.develz.crawl.desktop`
    `%{_prefix}/share/metainfo/org.develz.crawl.appdata.xml`
    `%{_prefix}/share/icons/hicolor/32x32/apps/crawl.png` (same for other available sizes and scalable)

Tiles
    `%{_prefix}/share/applications/org.develz.crawl_tiles.desktop`
    `%{_prefix}/share/metainfo/org.develz.crawl_tiles.appdata.xml`
    `%{_prefix}/share/icons/hicolor/32x32/apps/crawl-sdl.png` (same for other available sizes and scalable)

Note the desktop and appdata files follow the "reverse DNS" convention. Some tools like the one used to build the AppImages are very strict with the [specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html). That's why those names are not configurable.

**Comment by moozaad** [comment]
@robertxgray Appimage worked fine. Played a tab+o game to death. Loads highscore ok, sees and loads saved games fine.

If you're motivated for it, I would suggest also looking at flatpak as that is what fedora and opensuse appear to be standardising on for application deployment. 

Still to do the new linux build.

**Comment by robertxgray** [comment]
@moozaad The game is already available at Flathub, and looking at their resources I think we should do some changes.

- Use the "reverse DNS" convention also for icons.
- Rename or parametrize these resources. If only Debian requires different desktop files we can manage that exception when building the deb packages.
- We may also include release info in the appdata. However, I would like to know the opinion of the core developers about this because it requires maintenance.
-  The screenshots are outdated. I'll open an issue because I don't know any other official sources.

I'll try to have these changes available ASAP.

**Comment by rawlins** [comment]
> We may also include release info in the appdata. However, I would like to know the opinion of the core developers about this because it requires maintenance.

Can it be derived from tags somehow? We already do this for versioning the game in general; at this point aside from debs a release version is just a CI-generated artifact that has a release tag of the right format.

**Comment by robertxgray** [comment]
> Can it be derived from tags somehow?

They have included the release announcement in the metainfo's changelog. I don't know if github actions can scrape the information from wordpress, but I'm leaving it empty for now. With the latest changes they can still reuse the icons and most of the desktop file.

There's a new variable to set the name of the XDG resources. Flathub can use XDG_NAME=org.develz.Crawl to continue using the same files without the need to rename them.

The default values are:

- org.develz.Crawl_console
- org.develz.Crawl_tiles

I just built new AppImages and Debian packages to make sure nothing broke. They're available here: https://github.com/robertxgray/crawl/releases/tag/0.29.0

**Comment by rawlins** [comment]
how were the debs there built, was that in CI somehow?? (We would love to have that automated too.)

We are thinking of doing a 0.29.1 bugfix release immediately after the tournament ends, and so it might be nice to merge this branch first so that an AppImage gets built too at that point -- does that timeline work for you @robertxgray ? (I've looked it over and am willing to just merge it without fully vetting the linux stuff myself, it's languished long enough and it seems very useful to have the CI changes here.)

**Comment by robertxgray** [comment]
> how were the debs there built, was that in CI somehow??

Now I can answer yes to that question :grin:

I have included the files in another auto-generated release.
Sample here:

- https://github.com/robertxgray/crawl/releases/tag/0.29.0
- https://github.com/robertxgray/crawl/releases/tag/0.29.0-debian

I guess they could be installed in the repository instead if the required ssh keys are available in Github Secrets.

Debian packages and AppImages are only generated for releases.

A non-updated changelog seems to lead to packages with the wrong version. In order to avoid this, if you forget to update the changelog an automatic entry like this will be added:

> crawl (2:0.99.0-1) unstable; urgency=low
>     
>   * New upstream release.
>  -- Crawl bot <bot@crawl.develz.org>  Mon, 01 Jan 2022 12:12:12 +0000
> 

I agree with the merge if you are okay with the current status of this PR. I don't have any other pending changes ATM. Just waiting for feedback from @moozaad.

**Comment by robertxgray** [comment]
`GAME` is the name of the executable, but it's not the same for every distributor. For Flatpak and AppImages the name is just `crawl` like the console build because they're isolated and don't conflict. Fedora, Debian and Ubuntu use `crawl-tiles`.

The file `org.develz.crawl.desktop` was renamed in the commit that introduces the `XDG_NAME` variable. The default name is now `org.develz.Crawl_console.desktop`, but you can use the old name with `XDG_NAME=org.develz.crawl`. This variable also affects the icon and metainfo files.

Note the desktop file references the icon and the executable. The metainfo references the desktop file and itself. All these references are updated in the build process. You can rename the files after but you'll need to update the references too. It's easier to use the variables `GAME` and `XDG_NAME` to set the final file names.

- The default value for `GAME` is `crawl`.
- The default values for `XDG_NAME` are.
  - `org.develz.Crawl_tiles (if TILES=y)`
  - `org.develz.Crawl_console (otherwise)`

I was tempted to merge the tiles and console resources because they have minor differences, but I didn't like the idea of moving  the screenshot's urls to the makefile.

**Comment by moozaad** [comment]
Bottom line is; All good. 

Requires some adjustments to rpm spec files but nothing major.

I'm considering slicing up the packages a bit differently for opensuse but nothing to block this PR. Good work and thanks!

**Comment by moozaad** [comment]
Looking at KDE's discover. You might want to add <developer_name/> to the [metainfo](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html). Right now it shows "Unknown Author", which looks a little sad/sus. :)

https://flathub.org/apps/details/org.develz.Crawl just has a "-" for developer.

**Comment by robertxgray** [comment]
> You might want to add <developer_name/> to the [metainfo](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html).

Done.

**Comment by rawlins** [comment]
Thanks again for this! 0.29.1 artifacts here: https://github.com/crawl/crawl/releases/tag/0.29.1

For the debs, the content looks right, but they oddly have showed up on a release tag attached to the current trunk commit at the time that CI ran: https://github.com/crawl/crawl/releases/tag/0.29.1-debian

I've verified that the version is correct, despite this. I guess the upload action created the tag itself (and maybe https://github.com/svenstaro/upload-release-action/issues/63 is relevant). Do you know if I had created a 0.29.1-debian tag explicitly (I didn't) in advance would it have worked?

**Comment by robertxgray** [comment]
> Thanks again for this!

I'm happy to help.

> maybe [svenstaro/upload-release-action#63](https://github.com/svenstaro/upload-release-action/issues/63) is relevant

I agree, good find.

> Do you know if I had created a 0.29.1-debian tag explicitly (I didn't) in advance would it have worked?

It should work because it's the same situation as the normal releases and the action's code seems to confirm it.  Then consider removing the parameters `release_name` and `body` from `ci.yml#241` or the info you enter will be overridden.

**Comment by robertxgray** [comment]
@rawlins Aren't we missing the source packages in the release? I miss stone_soup-0.29.1-nodeps.tar.xz in particular because I'm working on the Flatpak build.

**Comment by moozaad** [comment]
Side note; the opensuse build uses the nodeps version. I could engineer around that if it's an issue.

**Comment by rawlins** [comment]
>  I miss stone_soup-0.29.1-nodeps.tar.xz in particular because I'm working on the Flatpak build.

Right now this file shows up only on the debian tag (https://github.com/crawl/crawl/releases/tag/0.29.1-debian) renamed as `
crawl_0.29.1.orig.tar.xz `. It doesn't get added to the main release tag.

We may reengineer this all a bit though. Currently under discussion would be to tar everything currently on the debian tag, and upload that with the other release downloads (even though it's not very end-user-friendly). If we do that we'd likely upload the nodeps package directly there as well.

**Comment by robertxgray** [comment]
Thank you, then I'll be using `crawl_0.29.1.orig.tar.xz` for now. No issues so far.

**Comment by robertxgray** [comment]
Fedora has also included the new resources in their packages:
https://src.fedoraproject.org/rpms/crawl/c/08dfd0d15dec0cb8e17a223781f873f596d71088?branch=rawhide

**Pull request merged**
