### PR TITLE
Change species' magic resistance to willpower.

### PR DESCRIPTION
**Pull request by pooka109**
This updates the species YAML files and associated documentation. "mr" is now "wl", to match the species aptitude header and footer.

(This time, without the breakage.)

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Just to check - are you the same David Lawrence Ramsey as dolorous? Would you like your commit bit back and an invite to the dev discord? It'd save some time merging PRs :)

**Comment by pooka109** [comment]
Yes, that's me. I finally got inspired again after about 11 years :)

And, yes, please. It would be nice to commit things myself again. I don't really have the energy for major code development anymore, but I can still contribute something.

As for Discord, that may be an issue. I have a very irregular schedule, which is why I was never on chat in the old days. (Are there other current dev communication channels that aren't always in real time? I'm on Reddit, if that helps.)

**Comment by PleasingFungus** [comment]
Sure, happy to have you back! I've sent you an invite to the dev team, which should let you merge your own changes.

> As for Discord, that may be an issue. I have a very irregular schedule, which is why I was never on chat in the old days. (Are there other current dev communication channels that aren't always in real time? I'm on Reddit, if that helps.)

Discord can be used asynchronously - it's not like IRC where you need to be online or you'll miss out on messages. If the email address that you have listed for your commits is valid, I can send you an invite there, and you can use it or not as you please :)

**Comment by pooka109** [comment]
Thank you!

And that's good to know. Yes, the email address is valid.

**Comment by pooka109** [comment]
So I can go ahead and merge this (and possibly the others), then?

**Comment by PleasingFungus** [comment]
Yes, go ahead! I had some small concerns about the arcanist -> wizard one, but it seems better than status quo & is easy to change again if we want.

**Comment by pooka109** [comment]
Thanks. Will do.

**Comment by pooka109** [comment]
Done.

(Although GitHub's "Merge pull request" button doesn't quite work the way I expected.)

**Pull request merged**
