### PR TITLE
New Decor Sprites

### PR DESCRIPTION
**Pull request by Ploomutoo**
Added a batch of 43 vault and decor sprites, including baked goods caches, flower pots, banners, fountains, and a mop

### CODE REVIEW

**Comment by regret-index** [comment]
These are really impressive tiles addressing a bunch of desired requests for art and I'll be merging them in post-0.32-tournament.

(From a technical perspective, I'm not entirely sure how I'd like to handle the description usage of a variety of these, but that can be determined on its own time. The wall banners, at the very least, probably should go into a different folder since they don't work as free-floating tiles.)

**Comment by PleasingFungus** [comment]
Hi! I was looking through recent art commits, and I can't find anything that confirms whether this (or the Ijyb splash screen, or the '[sunnier demon](https://github.com/crawl/crawl/commit/162e8f45799c1b617a27fd464c83e546ded0c584)' tile) is licensed under Crawl's [Creative Commons 0](https://creativecommons.org/publicdomain/zero/1.0/) license.

@Ploomutoo, do you mind saying whether or not you consent to licensing your work under CC0? Totally fine either way; it's just helpful for projects like the [tiles repo](https://github.com/crawl/tiles/) to have a clear licensing situation. If you choose not to license your tiles under CC0, that won't affect whether they're used for Crawl, just whether other people could use them for other projects in future.

Thanks for the contributions regardless! :)

**Comment by Ploomutoo** [comment]
@PleasingFungus Hi!
Yes I consent to licensing all of my submitted works under CC0

**Comment by PleasingFungus** [comment]
Great, thanks! :)

**Pull request closed without merging**
