### PR TITLE
donger sprites

### PR DESCRIPTION
**Pull request by christopherlandry**
palentonga sprites - did not overwrite centaurs, assuming someone wants to point those placeholders at these

### CODE REVIEW

**Comment by PleasingFungus** [comment]
These look great. We should merge em after t - thanks a ton!

**Comment by PleasingFungus** [comment]
(Working on merging this in now. It's not as simple as I'd thought but I'm still excited.)

**Comment by ebering** [comment]
We should wait to tag 0.26.1 until we can cherry-pick these!

**Comment by PleasingFungus** [comment]
Merged as 2a9d61b3d9209352f81f66656e013089fb886315 . Thanks loads!

**Pull request closed without merging**
