### PR TITLE
translation of source/dat/database/ko

### PR DESCRIPTION
**Pull request by sesangsokuro**
just added folder and translated files

### CODE REVIEW

**Comment by isloat** [comment]
Thanks for working on the Korean translation. Is this ready to be merged?

**Comment by sesangsokuro** [comment]
​not yet. ​there was not exist for english (in new database file
'misc.txt') , only for korean ( language = ko in init.txt ).
sorry.
please wait few days, i'll make this ( for english file )
thanks.

when i work complete, Can i send some email? where?

2017-02-02 4:40 GMT+09:00 Isaac Sloat <notifications@github.com>:

**Comment by isloat** [comment]
Just comment here once you're finished and the devs will get an email notification. Thanks again for your work!

**Comment by gammafunk** [comment]
We have instructions for MSYS2 in the official INSTALL.txt file:

https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.txt#L235

If there are changes you'd want to see to those instructions, please modify INSTALL.txt and put these in a new PR and not this one, since this PR is related to your translation patch.

**Comment by sesangsokuro** [comment]
I'll re-open about this pull request after more progress.
Thank you.

**Pull request closed without merging**
