### PR TITLE
Simplify code for changing pluses on mace of Variability.

### PR DESCRIPTION
**Pull request by amalloy**
All ye who think ifs are better for control flow than functions, speak now or forever hold your peace.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
"sword"? 😛

**Comment by amalloy** [comment]
@alexjurkiewicz A sword is just a mace with one very pronounced spike. 

Fixed.

**Comment by alexjurkiewicz** [comment]
Did you see the rework that @Hellmonk made for Hellcrawl? IMO it would be a better approach for vanilla too
https://github.com/Hellmonk/hellcrawl/commit/fd85efbddbe62bffad6dc0b8656ef4e665fadfce

**Comment by amalloy** [comment]
I agree the existing mechanics for Variability seem pretty dumb to me, for the reason hellmonk gives. The fix seems like a reasonable direction, although I don't know crawl's combat mechanics well enough to say that the particular numbers chosen result in the mace having an appropriate power level and variance. I'm not really inclined to port that change unilaterally, but if you mention it in `##crawl-dev` or open a new PR for it then someone who knows combat better than I do can express an opinion.

**Pull request merged**
