### PR TITLE
Re-imagining Robe of Augmentation as a ghostly shroud

### PR DESCRIPTION
**Pull request by theJollySin**
The [Robe of Augmentation](http://crawl.chaosforge.org/Robe_of_Augmentation) was no one's favorite unrandart, and the [wiki](https://github.com/crawl/crawl/wiki/Unrand-Review) suggests it needs change.  It was not particularly interesting; there weren't any big decisions to make when using it.

So I have re-imagined it as a ghostly shroud.  Ghosts are ephemeral, so I removed the boring `+4 Strength` on a cloth robe and replaced it with `Stealth++`.

More interestingly, I added `rTorment`, which on the surface is so rare players will be falling over themselves to wear the robe.  However, the robe is also Fragile, so once you put it on, you have to eat the generally meh caster stats permanently.  I also fancy stabbers will try to wear this item, though that's just a terrible idea for melee survivability.

Lastly, I made the item Holy, so some God/species combinations won't be able to use it.

I'm happy for any criticism.  I'm sure content changes have their finer points, and can get contentious.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
I think this is a definite improvement over the status quo (anything would be!). Some specific feedback:

* +dex, +int, +stealth, and holy seem a little extraneous. You could remove them to tighten up the clarity of this item.
* I'm not sure if Fragile is too important -- armour swapping is slow and this isn't any worse than finding eg Skin of Zhor or Salamander Hide.
* It's good how this item encourages blaster casters to consider rTorment vs archmagi. But for other character archetypes, it's a useless item. If you used a heavier base armour type, there would also be consideration of rTorment vs higher enchanted equivalent of the same base type. Perhaps leather or a light dragon armour?

**Comment by semitonal** [comment]
I'm not entirely sure about rTorment on an unrand (the [crown of Eternal Torment](https://github.com/crawl/crawl/commit/dcab04f1b94a6a4f18d882a66ed2b73608a172d3) tried this in the past and has since been removed, it's not helped by being a property that tends to get pretty heavily overvalued), but either way it doesn't appear that this PR implements rTorment currently, it just adds it to the unrand inscription. I also don't believe there's any handling to stop undead races from equipping holy armour, or to give penance for wearing them under evil gods - only weapons are handled currently.

**Comment by theJollySin** [comment]
> I'm not entirely sure about rTorment on an unrand

Well, if we don't want rTorment on an unrand, we can close this PR. It was an idea.

> either way it doesn't appear that this PR implements rTorment currently, it just adds it to the unrand inscription

Sorry?

> I think only weapons are handled, since that's the only type of holy equipment that currently exists.

The 'holy' modifier only works on weapons?  I certainly didn't know that. I'll build the game locally again and test that out.  News to me, but if so, helpful, thanks.

**Comment by theJollySin** [comment]
> I think this is a definite improvement over the status quo (anything would be!). 

Agreed

>  +dex, +int, +stealth, and holy seem a little extraneous. You could remove them..

Remove all of those? So it would literally just be a rTorment robe, with no other stats?

>   I'm not sure if Fragile is too important

Basically, I thought that if I put `rTorment` on an unrandart that didn't have some serious drawbacks, the PR would be closed immediately.

The question is: how do we make the choice of whether or not to wear an `rTorment` item interesting. Just spit-balling.  Obviously, any player who finds a ring that just says `rTorment` on it will pick the ring up. Now, I'm actually not against that, players would still have to fight the RNG to find such a ring.  But if that ring is Fragile or... say... has *Drain upon removal, then suddenly the choice of when to wear that ring is more Interesting.

>  It's good how this item encourages blaster casters to consider rTorment vs archmagi. But for other character archetypes, it's a useless item.

Sure, no MiBe would not want to wear this.  But the Wiki clearly states that unrandarts should be very enticing to some characters, but not all.  It's worth noting that nearly all the unrandarts are focused at a smaller subset of all possible build/character combinations. Even the jewelry isn't generally great for all players.

**Comment by sdynet** [comment]
Some ideas:
1. Steam dragon scales-based items. If I see dragon scales{rTorment} when I play a warrior, I'll be serious about changing my play style. I think it would be fun to give warrior a chance to change play style.
2. Sometimes cast the Shroud of Golubria.
3. Give +8 Dex, Running brand.
4. Double evasion.

**Comment by theJollySin** [comment]
>     1. Steam dragon scales-based... {rTorment} ...
>     2. Sometimes cast the Shroud of Golubria.
>     3. Give +8 Dex, Running brand.

I like all three of those.  Maybe we could fix/replace Robe of Augmentation AND Rove of Misfortune.

**Comment by theJollySin** [comment]
> 1. Steam dragon scales-based items. If I see dragon scales{rTorment} when I play a warrior, I'll be serious about changing my play style. I think it would be fun to give warrior a chance to change play style.

Okay, how about:

    +0 Shadow Dragon Scales {rTorment}

On the one hand, it's a pretty great item for certain players in extended. But, more importantly, I think it would entice both clothie-blaster-casters and melee dudes alike to significantly change their original character plan and go a new direction.

**Comment by semitonal** [comment]
> > either way it doesn't appear that this PR implements rTorment currently, it just adds it to the unrand inscription
> 
> Sorry?

You've added the `INSCRIP: rTorment` line, but INSCRIP lines are purely cosmetic - they're just for adding extra notes to an unrand's inscription. Any special effects they describe still need to be implemented in code elsewhere (in this case, in `player_res_torment()` in player.cc).

**Comment by alexjurkiewicz** [comment]
> Sure, no MiBe would not want to wear this. But the Wiki clearly states that unrandarts should be very enticing to some characters, but not all. It's worth noting that nearly all the unrandarts are focused at a smaller subset of all possible build/character combinations. Even the jewelry isn't generally great for all players.

That's fair. I was thinking you could pick a base type with a higher base ER that would make it attractive to both blaster casters and a few character types that wear slightly heavier armour. You probably couldn't make the armour useful for plate armour wearers as well, but I think light/medium armour could be worthwhile. On that note, shadow dragon armour is 15 ER, so that would seem to rule out blaster casters now...! I was thinking something like QDA (7 ER).

**Comment by theJollySin** [comment]
> You've added the `INSCRIP: rTorment` line, but INSCRIP lines are purely cosmetic - they're just for adding extra notes to an unrand's inscription. Any special effects they describe still need to be implemented in code elsewhere (in this case, in `player_res_torment()` in player.cc).

Oh, thanks so much.   That's really helpful.  I'm reasonably embarassed.

**Comment by theJollySin** [comment]
> On that note, shadow dragon armour is 15 ER, so that would seem to rule out blaster casters now...! I was thinking something like QDA (7 ER).

Yeah, I didn't realize that until a few minutes after I wrote it.  Quicksilver is a lot better for a happy medium, yeah.

**Comment by ebering** [comment]
I don’t think changing the base type fundamentally addresses the problem @semitonal pointed out in an understated way. Torment resistance doesn’t work well on items. Torment is primarily a late game threat, and there are many alternatives for addressing the threat at that point. Before then it’s rare enough that it’s not worth an item slot. 

I’m going to close because PR comments (which send notifications to the entire dev team) aren’t the best place for spitballing and brainstorming; I’m happy to iterate on augmentation ideas in IRC.

Some closing food for thought: Misfortune’s current form is a part of the untamed revision in line with the guidelines on the wiki page. Consider it an example rather than something to replace!

**Pull request closed without merging**
