### PR TITLE
Give atropa and datura darts distinct color tiles

### PR DESCRIPTION
**Pull request by Goratrix**
Currently both atropa and datura are using default branded dart tile,
which is dark blue. This gives them distinct colors, orange for datura
and lighter blue for atropa. The default branded tile (not used) is
changed to grey/silver instead of blue.

### CODE REVIEW

**Comment by Goratrix** [comment]
Sample:

darts

**Comment by Goratrix** [comment]
Yep, original dark blue looks better:

darts2

**Comment by PleasingFungus** [comment]
Hello! Sorry for the extremely slow response here. This PR sounds great. Do you give permission for your altered tiles to be used under DCSS's Creative Commons license?

**Comment by Goratrix** [comment]
Yes, no problem, I already did a few contributions in the past, so these things are sorted out.

**Comment by PleasingFungus** [comment]
Great, thanks!

**Comment by Goratrix** [comment]
Merged as d41f7fe, closing.

**Pull request closed without merging**
