### PR TITLE
Enable `make test` on GHA, remove Travis

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
This PR has commits doing three things:

1. Run `make test` in GitHub Actions
    1. (Note: this is ONLY for current TAG_MAJOR_VERSION. There are several failures with TAG_MAJOR_VERSION 35 I don't know immediately how to solve.)
2. Colourful IRC messages 🌈 
2. Delete all Travis CI config (`make test` was the last thing that GitHub Actions lacked.*)
3. Fix up some `TAG_MAJOR_VERSION 35` issues I found. These aren't strictly related to the first two points, but I found them while working on this PR and it doesn't seem too critical to pull them out. If you'd like me to I can though.

\* GHA also lacks testing of `util/util/monster`, but I don't think this is important. Let me know if you'd like a test added for it.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
The `TAG_MAJOR_VERSION 35` builds have a bunch of `make test` failures which I am not immediately sure how to solve.

**Comment by alexjurkiewicz** [comment]
After several rebases, this should be passing and is ready to merge. I've edited the OP with a more complete description of the PR.

**Comment by alexjurkiewicz** [comment]
OK, **now** the build is good.

**Comment by aidanholm** [comment]
Thanks, this looks good! I've pulled out the dead code removal / tag 35 commits into a separate branch, and will merge that manually.

Could you rebase and organize the remaining CI related commits? It'd help to have some additional context for some of them, e.g. for "Only run 'make test' for console builds" it'd help to describe why in the commit description.

Also, a test for `util/util/monster` would be very much appreciated if possible! Cheers

**Comment by alexjurkiewicz** [comment]
Sure. Travis CI tests `monster` by seeing if it can successfully generate a
hardcoded monster (orb guardian). Any ideas on a better test?

**Comment by aidanholm** [comment]
Something like that is probably fine for now I reckon

**Comment by aidanholm** [comment]
I rebased and squashed most of this into master; the only unmerged commit is the one removing travis support.

**Pull request closed without merging**
