### PR TITLE
Remove throwables ammo brands(poison, steel)

### PR DESCRIPTION
**Pull request by sdynet**
They are removed to reduce inventory pressure.

### CODE REVIEW

**Comment by ebering** [comment]
While I appreciate your enthusiasm, it would be helpful if you could be patient and learn to work with the GitHub tools instead of closing a PR and opening a new one for every new change. 

From one of your previous PRs you posted this error message:

```
$ git push --set-upstream origin throwing
remote: Permission to crawl/crawl.git denied to sdynet.
fatal: unable to access 'https://github.com/crawl/crawl.git/': ```

You need to set up to push to `sydent/crawl` on GitHub as your target remote. Since I don't know how your local system is configured I can't tell you what remote name that has. If you could show me the output of `git remote show` I might be able to help.

**Comment by sdynet** [comment]
I entered it. Printed as follows:
Administrator@ADMINIS-SDY MINGW64 /d/crawl (throwing)
$ git remote show
origin
sdynet

**Comment by ebering** [comment]
Ok, for future reference, when you want to force-push to update a pull request (after rebasing, or editing a commit), or regularly push to add new changes, you need to push to the repo `sydent/crawl`. I'm guessing based on the remotes you've named this remote `sydent`. So to update this pull request, you would (after making changes) use

```
git push sydent throwing
```

Or, if you've done something that requires force pushing, add the `--force` option.

**Comment by sdynet** [comment]
Thank you for your kind explanation. :)
I have nothing to change in this commit, but I will refer to it when I ask for a new pr later.

**Comment by ebering** [comment]
Thanks for the patch. I've incorporated this into the bigger throwing overhaul in #1062 so I'm closing this PR. How would you like to be listed in CREDITS.txt?

**Comment by sdynet** [comment]
I'd like to have a sdynet, please. :)

**Comment by sdynet** [comment]
> Thanks for the patch. I've incorporated this into the bigger throwing overhaul in #1062 so I'm closing this PR. How would you like to be listed in CREDITS.txt?

I'd like to have a sdynet, please. :)

**Pull request closed without merging**
