### PR TITLE
Surely Yiuf has collected some decent hammers.

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Occasionally drop a `good_item hammer` in Yiuf's hut.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
(The only brand hammers seem to gen with is protection. I'm not sure why.)

**Comment by cbuchananhowland** [comment]
Yiuf's hammers can already generate as artefacts, and every now and then 
one of those can be quite good.

**Comment by alexjurkiewicz** [comment]
Yeah, but much more rarely than this patch.

**Comment by PleasingFungus** [comment]
Consensus in ##crawl-dev was that this was excessive; Yiuf already has plenty of loot.

**Pull request closed without merging**
