### PR TITLE
Add code coverage tracking

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Add code coverage tracking

Supports both GCC and LLVM toolchains.

Bluffer's guide:
1. make catch2-tests
2. util/coverage

More explanation has been added to testing.md (which reworks
testing.txt) and `util/coverage --help`.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
llvm-cov:
Screen Shot 2019-12-30 at 4 15 52 pm
Screen Shot 2019-12-30 at 4 16 02 pm
Screen Shot 2019-12-30 at 4 16 08 pm

lcov:
Screen Shot 2019-12-30 at 4 19 43 pm
Screen Shot 2019-12-30 at 4 19 51 pm
Screen Shot 2019-12-30 at 4 19 58 pm


gcovr:
Screen Shot 2019-12-30 at 4 20 56 pm
Screen Shot 2019-12-30 at 4 21 02 pm
Screen Shot 2019-12-30 at 4 21 05 pm

**Comment by aidanholm** [comment]
Awesome! :sunglasses: 

Minor nit: there's some extra whitespace changes to the Makefile; i'd prefer they were made as a separate commit; it makes reviewing and rebasing easier.

Separately, I'd prefer that COVERAGE be enabled by default on all debug builds, and would even prefer not exposing a COVERAGE option at all unless there's a good reason. In general I think keeping the number of build options to a minimum is best.

**Comment by alexjurkiewicz** [comment]
> Separately, I'd prefer that COVERAGE be enabled by default on all debug builds, and would even prefer not exposing a COVERAGE option at all unless there's a good reason. In general I think keeping the number of build options to a minimum is best.

makes sense. Compilation is only ~10% slower

**Comment by reaverb-Crawl** [comment]
Merging into master after testing locally. Thanks for the code!

**Pull request merged**
