### PR TITLE
Fix holy word scroll (11821)

### PR DESCRIPTION
**Pull request by 1Hyena**
When reading the holy word scroll, the player is now warned in
case there are friendly unholy creatures around. Also, another
warning dialogue is spawned if reading the scroll would put the
player under penance.

### CODE REVIEW

**Comment by ebering** [comment]
One last question, how would you like to appear in CREDITS.txt?

**Comment by ebering** [comment]
Merged with some tweaks, let me know how you'd like to appear in credits.

**Comment by 1Hyena** [comment]
Thanks! By solving this task I learned quite a lot about the engine. While I can't promise periodic contributions, I do know that sometimes it can happen that I have free time and a desire to help crawl at the same time, so now that I know the drill it's very likely that we will talk again ;) As for the credits, you can refer to me by my full name (Erich Erstu).

**Comment by 1Hyena** [comment]
@ebering 
by the way, shouldnt https://crawl.develz.org/mantis/view.php?id=10686 also be marked done now?

**Pull request closed without merging**
