### PR TITLE
Don't create Qaz clouds over firewood

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
The messages generated by burning/freezing flora made resting in certain
places (especially lair) quite noisy/tedious.

Hopefully doesn't prevent any cool tech?

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Doesn't compile... (Also, the comment should explain the reasoning, briefly. "Don't create clouds over firewood; too spammy!")

**Comment by alexjurkiewicz** [comment]
Fixed compilation somehow. I `s/noisy/spammy/` in the commit message, does that help?

**Comment by PleasingFungus** [comment]
This will crash the game if there's no monster at the given position.

**Comment by alexjurkiewicz** [comment]
Fixed, thanks for your code help

**Pull request merged**
