### PR TITLE
A simple Bitcoin meme arrival vault

### PR DESCRIPTION
**Pull request by MalcolmRose**
I haven't used git in awhile, hopefully I didn't do anything wrong here. Let me know.

### CODE REVIEW

**Comment by MarvinPA** [comment]
I don't think this is a good vault idea.

**Comment by MalcolmRose** [comment]
It depends on what you mean. Ascii art? Sure. But there are lots of symbols in Crawl. This is just a symbol. There's a dollar sign Gozag altar vault, ampersands and such (which admittedly have to do with roguelike history, but still). I'm unclear on how this is any different.

**Comment by alexjurkiewicz** [comment]
This is a real world reference, which crawl generally tries to avoid. It
also references a meme and a specific technology, which will date over time.

**Comment by MalcolmRose** [comment]
There is a new PR now based on the feedback given here. https://github.com/crawl/crawl/pull/699

**Pull request closed without merging**
