### PR TITLE
New single-use item: Shattersphere

### PR DESCRIPTION
**Pull request by PleasingFungus**
Shatterspheres are single-use evocables that cause a radius 2 explosion at
range 3. Their explosion is skewed by 1 tile from the target, so they always
have at least a 1/3 chance of hitting the player. However, since they do
6d12 BEAM_FRAG damage, players with 20-25 AC will usually take little to
no damage. (BEAM_FRAG checks 3x AC.) As such, this is intended to be a fun
toy for well-armoured characters and a desperation option for others.

A design space that I've wanted to explore for many years is the
'3x AC' damage type (ala LRD and the late, lamented Orb of Fragmentation).
I initially tried to make it into a spell, but it's very much the opposite
of the modern Earth school philosophy and in general makes more sense as a
tool for armoured, less-spell-focused characters.

Other notes:
- The targeter intentionally doesn't prompt that you might hit yourself;
  that's guaranteed.
- Shatterspheres use V and let you train evocations, but they aren't
  affected by evocations skill at all. (This is because increased damage
  is arguably a downside, since it means your AC might not be able to
  soak it.) Some possible fixes: turn it into a multi-use item ala box of
  beasts and have evocations skill change odds of it breaking; add a fail
  chance (though the UI is bad); turn it into a quivered, thrown item (but
  the code for this seems much trickier).

Fun comparison link: https://github.com/crawl/crawl/tree/shrapnel

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
# [Codecov](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=h1) Report
> Merging [#1282](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=desc) into [master](https://codecov.io/gh/crawl/crawl/commit/d0718851208b96d3b45e1f55a56ed0b685cb1810&el=desc) will **increase** coverage by `0.00%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master    #1282   +/-   ##
=======================================
  Coverage    2.92%    2.93%           
=======================================
  Files         404      404           
  Lines      136659   136698   +39     
  Branches    62821    62835   +14     
=======================================
+ Hits         4003     4007    +4     
- Misses     130219   130256   +37     
+ Partials     2437     2435    -2     
```

| Flag | Coverage Δ | |
|---|---|---|
| #catch2 | `2.93% <4.65%> (+<0.01%)` | :arrow_up: |

| [Impacted Files](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [crawl-ref/source/item-name.cc](https://codecov.io/gh/crawl/crawl/pull/1282/diff?src=pr&el=tree#diff-Y3Jhd2wtcmVmL3NvdXJjZS9pdGVtLW5hbWUuY2M=) | `11.27% <0.00%> (+0.16%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=footer). Last update [d071885...d80106d](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by sdynet** [comment]
I compiled your Branch, but it failed. What's the cause?
[](https://drive.google.com/open?id=1IN8JePxgUneQ8yYTpVR2W1d6QMcgPqmV)

**Comment by PleasingFungus** [comment]
That's very odd, and doesn't look related to this PR. I haven't changed the files mentioned in that link. Can you build master?

**Comment by sdynet** [comment]
Oh, sorry. I was mistaken about the branch.

**Comment by PleasingFungus** [comment]
No worries!

**Comment by rawlins** [comment]
ok, so this codecov thing seems cool in principle but multiple comments in a single PR thread (or any github comments at all, tbh) is a bit excessive...

**Comment by alexjurkiewicz** [comment]
# [Codecov](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=h1) Report
> Merging [#1282](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=desc) into [master](https://codecov.io/gh/crawl/crawl/commit/d0718851208b96d3b45e1f55a56ed0b685cb1810&el=desc) will **increase** coverage by `0.00%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master    #1282   +/-   ##
=======================================
  Coverage    2.92%    2.93%           
=======================================
  Files         404      404           
  Lines      136659   136699   +40     
  Branches    62821    62836   +15     
=======================================
+ Hits         4003     4006    +3     
- Misses     130219   130259   +40     
+ Partials     2437     2434    -3     
```

| Flag | Coverage Δ | |
|---|---|---|
| #catch2 | `2.93% <6.25%> (+<0.01%)` | :arrow_up: |

| [Impacted Files](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [crawl-ref/source/item-name.cc](https://codecov.io/gh/crawl/crawl/pull/1282/diff?src=pr&el=tree#diff-Y3Jhd2wtcmVmL3NvdXJjZS9pdGVtLW5hbWUuY2M=) | `11.21% <0.00%> (+0.10%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=footer). Last update [d071885...a36353c](https://codecov.io/gh/crawl/crawl/pull/1282?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
