### PR TITLE
Background creation

### PR DESCRIPTION
**Pull request by aedyr**
Adds some notes on menu setup and spacing when adding new backgrounds. Also add instructions to edit species yaml files so that recommendations work in both directions.

### CODE REVIEW

**Comment by aedyr** [comment]
Added additional commit to convert this file to Markdown.

**Comment by PleasingFungus** [comment]
Merged, thanks! Minor note: in future, please try to wrap lines to 80 characters. :)

How would you like to be credited in the `CREDITS`?

**Comment by aedyr** [comment]
> Merged, thanks! Minor note: in future, please try to wrap lines to 80 characters. :)
> 
> How would you like to be credited in the `CREDITS`?

Thanks, sorry about that! Sam Willett is fine for credits.

**Comment by PleasingFungus** [comment]
Added, thanks!

**Pull request closed without merging**
