### PR TITLE
Webserver: Enhance lobby_remove message

### PR DESCRIPTION
**Pull request by syranez**
Hi, iam currently writing https://github.com/syranez/dcss-lobby which connects to a dcss server and listens to lobby-messages. dcss-lobby parses the messages and gives them in an edited form for further processing. The lobby_remove message does not give any information, why some player got removed from the lobby, thus:

The lobby_remove message contains now additionaly this three attributes:

* reason: the players cause for exiting the game ("saved", "bailed out", "dead")
* message: exit message if the reason is not "saved". Otherwise it is
null.
* dump: contains an url to the final morgue file or player morgue
directory if game is not finished yet.

### CODE REVIEW

**Comment by rawlins** [comment]
I haven't had a chance to look at it in detail yet but this looks like a useful change.

For the overall project, just to check, do you know about the milestone/logfile formats? That's the "official" way that most (but not all) of this information is distributed by servers, and it works for servers that use a non-standard webtiles (CPO) or don't use webtiles at all (CDO). You can see some examples here: https://crawl.kelbi.org/crawl/meta/git/

**Comment by syranez** [comment]
> I haven't had a chance to look at it in detail yet but this looks like a useful change.
:)

> For the overall project, just to check, do you know about the milestone/logfile formats? That's the "official" way that most (but not all) of this information is distributed by servers, and it works for servers that use a non-standard webtiles (CPO) or don't use webtiles at all (CDO). You can see some examples here: https://crawl.kelbi.org/crawl/meta/git/
Thank you. I did not know about the milestone/logfile formats. I am playing webtiles only and used to have the information the lobby has, which is sufficient for Me except that lobby_remove does not say, why it was emitted.

**Comment by syranez** [comment]
> For the overall project, just to check, do you know about the milestone/logfile formats? That's the "official" way that most (but not all) of this information is distributed by servers, and it works for servers that use a non-standard webtiles (CPO) or don't use webtiles at all (CDO). You can see some examples here: https://crawl.kelbi.org/crawl/meta/git/
I've looked into it and it seems milestone and logfile are increasing files with the data to the games of a version. dcss-lobby is a live announcer: starting a game, observing changes, and pausing/finishing - like the lobby does.

**Comment by alexjurkiewicz** [comment]
Nice stuff! If you haven't seen it, there is also a Python app which can connect to lobbies which might appreciate this change: https://github.com/gammafunk/beem

**Comment by ebering** [comment]
Not sure why this sat for so long, sorry about that. Hopefully its merge now is still useful to you.

**Pull request merged**
