### PR TITLE
Add one vault to simple.des

### PR DESCRIPTION
**Pull request by mainiacjoe**
mainiacjoe_arrival_cupid_arrowhead is a medium-sized, empty, heart-shaped room with three exits and a perimeter hallway for pillar-dancing.

This vault is the example project in a tutorial I'm writing about how to submit vaults to Crawl.

### CODE REVIEW

**Comment by mainiacjoe** [comment]
On #crawl-dev today, you reminded me that pulls should be made from branches of my fork, not from my fork's master as I did here.  Is there a way to fix this PR now, or just wait until the next one to "do it right"?

**Comment by mainiacjoe** [comment]
And now I see why: when I updated my origin:master from upstream:master earlier this evening, that commit got bundled into this PR because this PR is on master.

**Comment by mainiacjoe** [comment]
I'm going to close this PR because of the trouble caused by making a PR from :master.  I'll redo my tutorial to reflect making each PRs from its own branch and make a new PR.  Thank you for your help.

**Comment by rawlins** [comment]
>  Is there a way to fix this PR now

In case you didn't get an answer already, not really, but it's fine to do the following: (i) close the PR, (ii), move the commit to a branch, (ii-b) reset your master to be in sync with upstream, (iii) open a new PR against the branch.

**Pull request closed without merging**
