### PR TITLE
Codecov Tweaks

### PR DESCRIPTION
**Pull request by alexjurkiewicz**

### CODE REVIEW

**Comment by aidanholm** [comment]
Thanks for the PR! Unfortunately, I'm not sure this is actually worthwhile ... personally, I'm not especially interested in coverage unless tests pass, mostly because the data isn't necessarily accurate.

Separately, we probably want to exclude catch2-tests themselves from the code coverage report :)

**Comment by alexjurkiewicz** [comment]
I've added two more commits to disable Codecov PR comments and exclude unit tests themselves from coverage data.

I've left "always upload coverage data to Codecov" in, pending any feedback from @reaverb-Crawl (who might have some, being the catch2 integrator). But I'll rebase to remove if it's still not liked.

**Comment by rawlins** [comment]
The change that I requested looks good; I don't know enough about codecov to understand the implications of the first commit in this PR though.

**Comment by alexjurkiewicz** [comment]
TODO:

- [ ] ccache size limits

**Comment by ebering** [comment]
Looks like the outstanding todo was done. I'll merge this and be online in case I broke GitHub.

**Pull request merged**
