### PR TITLE
Make species-gen.py explicitly depend on python3

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Rather than "python".

Currently this script works with both major versions, so `python` was
specified to use whatever version is installed. But we are starting to
see OSes that install Python 3 only with a python3 name and no python
shortcut. For example, macOS Catalina (10.15), and possibly msys mingw
on Windows.

This new behaviour follows recommendations from the Python project (PEP
394), so is likely to become more prevalent over time.

---

Older webtiles servers (CAO, CDO) may not have Python 3 already
installed, so will need some manual intervention.

If getting Python 3 on these servers proves too difficult, the build process could be changed to initialise a Python virtualenv and run the command within that (to guarantee the existence of a `python` binary). But this would add complexity to everyone else's build.

### CODE REVIEW

**Comment by Goratrix** [comment]
Regarding MSYS2 on Windows, as I mentioned [here](https://github.com/crawl/crawl/pull/1250) they went the opposite direction and now use only 'python' as default everywhere instead of the versioned shortcuts. But I guess it's aliased, so python3 should work regardless.

**Comment by ebering** [comment]
I don't have admin access to CAO and CDO, so I don't know if they have `python3`

I'm not sure it's the pythonic approach, but it might be better from a crawl infrastructure standpoint to have the makefile explicitly call `$(PYTHON) species_gen.py` and deal with setting `$(PYTHON)`

@rawlins or @gammafunk are definitely the ones to weigh in here.

**Comment by alexjurkiewicz** [comment]
> I'm not sure it's the pythonic approach, but it might be better from a crawl infrastructure standpoint to have the makefile explicitly call $(PYTHON) species_gen.py and deal with setting $(PYTHON)

That seems good to me. I'll send a patch

**Comment by alexjurkiewicz** [comment]
Rebased and squashed. Thanks for the idea.

**Comment by ebering** [comment]
It looks like this is failing the check because the macOS environment has python3 but the pip dependency install is getting yaml for python2? I'm not 100% sure. Don't have time for a local build to investigate atm.

**Comment by alexjurkiewicz** [comment]
Yep, that looks like it. The CI runner has a bunch of useful software installed by default. Should be fixed... 🤞

**Pull request merged**
