### PR TITLE
Add a nostalgic hats-only shop

### PR DESCRIPTION
**Pull request by mainiacjoe**
This is a themed shop that has only hats.  The nostalgia is that the shop owner is Wiglaf.  He has collected a few quite nice hats over the years but now that he isn't adventuring anymore he wants to sell these to fund his retirement.  The Lua code intends that there be two ego hats, two randart hats, and either a single unrand hat or third randart hat.  These hats use the rare hat tiles without duplication.  DEPTH is set deep because these are nice items, though a shallower placement and high greed would work too and maybe be more thematic.

### CODE REVIEW

**Comment by pooka109** [comment]
If you want to place this on the final floors of the S-branches (Swamp, Shoals, and Snake, I assume?), the DEPTH: syntax for those places appears to be:

Swamp:$, Shoals:$, Snake:$

**Comment by mainiacjoe** [comment]
I didn't have the colon between the branch name and $ duh

**Comment by pooka109** [comment]
No problem.

**Comment by PleasingFungus** [comment]
Fun theme! Unfortunately, I'm not a vault dev, so will have to defer review.

Don't forget to run util/checkwhite. :)

**Pull request closed without merging**
