### PR TITLE
New morgue section `screenshots`

### PR DESCRIPTION
**Pull request by giann**
Notes can have an associated screenshot. For now only user notes take
screenshots. They are printed out in the `screenshots` section of the
morgue.

### CODE REVIEW

**Comment by giann** [comment]
- [ ] add ansi colors

**Comment by ebering** [comment]
The limit of screenshots to one per turn is still desired. Looking through this it looks like you'll also need some save compatibility code: when you unmarshallString to load the screenshot this should be wrapped in a TAG_MINOR check, you can see the adjacent packed level code for a quick example.

I would like to add this to 0.25, if you have the time to make the changes great, otherwise I will try to get to it.

**Comment by giann** [comment]
I'll try and look into it

**Comment by giann** [comment]
Done. @ebering not sure I should have added a new tag for the version check. Let me know.

**Comment by ebering** [comment]
Yes, any incremental shift in the binary format of the save file (which saving the screenshots requires) should be accompanied by a new tag. The CI is mad at you because you didn't wrap your if statement in a preprocessor, so when the tag-major-upgrade script is run it breaks the build. I've fixed that.

Thanks for the patch!

**Comment by giann** [comment]
👍

**Pull request closed without merging**
