### PR TITLE
 Clean up duplicate code at ability.cc 

### PR DESCRIPTION
**Pull request by anch0vy**
Remove duplicate your_talents call. And change condition check order.

### CODE REVIEW

**Comment by neilmoore** [comment]
The double-call is intentional, so that if you are confused but don't have any abilities, it will tell you that you have no abilities rather than that you are too confused.  I would keep it as is, but I'm leaving this open so others can comment.

**Comment by anch0vy** [comment]
I missed that case. sorry.
But I think It is okay to show "you are too confused" message before no ability message.
Because confused state is more important than no ability state. And beginner can know that ability can not use in confused even at no ability state.

**Comment by neilmoore** [comment]
A reasonable argument; also, the exceptions (abilities that can be used while confused) are all god abilities, and you can never have a god and have *no* abilities (since Renounce Religion is always there, even if unavailable).

**Comment by neilmoore** [comment]
It's in, thanks!

**Pull request closed without merging**
