### PR TITLE
replaced jackal sprite with a less deerish one

### PR DESCRIPTION
**Pull request by robbiemu**
I hand manipulated output from dreamstudio.ai

https://dreamstudio.ai/terms-of-service

to whit:
```md
# Ownership of Content; Stability Use of Content

As between you and Stability, you own the Content that you generate using the Services to the extent permitted by applicable law.
```

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Thanks, but we won't be using LLM-generated content in Crawl any time soon.

Appreciate the contribution anyway! :)

**Comment by robbiemu** [comment]
@PleasingFungus hi, I can appreciate that if that is the reasoned logic -- but I'm curious, what policy or rationale are you exercising? As clearly indicated, I modified this work substantially, and I demonstrated that I own the rights to the image submitted.

**Comment by PleasingFungus** [comment]
You have not demonstrated that you own any rights to the image. The quote you posted has zero informational content.

There are both legal and ethical issues with LLM-generated content that the DCSS dev team has zero intention of getting entangled with. Apologies for any disappointment.

**Comment by rawlins** [comment]
Happy to have contributions like the tile itself, but I don't think that the legalese quoted says what you think it does. Without knowing the "applicable laws" it guarantees almost nothing, and the legal situation in the US (probably in EU also) is incredibly murky at best.

**Comment by robbiemu** [comment]
> Happy to have contributions like the tile itself, but I don't think that the legalese quoted says what you think it does. Without knowing the "applicable laws" it guarantees almost nothing, and the legal situation in the US (probably in EU also) is incredibly murky at best.

Okay, I understand now, crawl is avoiding accepting any AI-generated content because ownership in AI generated art has not been substantiated in courts, its not a question of a claim of ownership between me and the model provider, rather the concern is that a third party could claim the generated art is derivative.

On basis of derivative works, you can't even see a work and then "create your own", as that also is derivative, so I can't just draw it by hand myself, either, I assume (I know that _would_ be assailable in court in the USA).

**Comment by rawlins** [comment]
I think the legal issue is a bit simpler: we want contributors to be legally able to grant permission for the project to use it (for art, preferably under a CC0 license but that's not a strict requirement). In this case, we don't see how the dreamstudio license puts you in a position to do this at all, because its grant of ownership is completely contingent on unspecified (and perhaps even as yet undetermined) laws (though for US law, [see](https://www.reuters.com/legal/ai-generated-art-cannot-receive-copyrights-us-court-says-2023-08-21/), no idea how this interacts). The fact that it's a derivative work of something in this legal state is extra.

More generally, at least some devteam members do have ethical concerns about AI-generated art. See e.g. https://kotaku.com/ai-art-dall-e-midjourney-stable-diffusion-copyright-1849388060 (there's a lot written on this).

**Comment by robbiemu** [comment]
dreamstudio's license is not for the art. it is for the ai model and website. the art, as it states, is mine (so far as they are concerned - I totally agree with you, that the ownership question is unresolved in at least the USA - this is _because_ the art the model generates could be seen as _derivative_, as Stålenhag in your article points out)

**Comment by rawlins** [comment]
You own it "to the extent permitted by applicable law", no?

**Comment by robbiemu** [comment]
@rawlins let me prefix this by acknowledging the and thanking you all for the additional info, which I feel was answered fully.

that statement maximizes the applicability of the license to use the site in general, not lessens the claim of ownership. if there are contradictions found in a license, it draws into question the validity of the entire document. if they cannot avoid being held accountable for derivative use in some instance, they still want the document to remain intact. it can be seen as a way of acknowledging that they might be held accountable for the making of it, before the resulting image (and with it, its ownership) has been transferred to the artist.

**Pull request closed without merging**
