### PR TITLE
fix: add support for Haiku

### PR DESCRIPTION
**Pull request by Crestwave**
This patch is currently being used in the official Haiku package repo (https://github.com/haikuports/haikuports/pull/6114, https://github.com/haikuports/haikuports/pull/6118)

[This patch](https://github.com/Crestwave/haikuports/blob/65ca2d9c37210996f9f7f91b3cbdb339f12b79cb/games-roguelike/crawl/patches/crawl-0.27.0.patchset) can alternatively be used if it's too messy splitting the documentation from the data directory

### CODE REVIEW

**Comment by Crestwave** [comment]
Screenshots:

**Comment by ebering** [comment]
Hi, thank you for porting crawl to Haiku. None of the devteam members have a haiku set up to easily test this on, so we would be unable to fix this should it break in the future.

That said, it appears to work based on your provided links and be the appropriate solution, so I'm happy to include it if you could update this PR to include Haiku specific build instructions in [INSTALL.md](https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md).

**Comment by Crestwave** [comment]
> Hi, thank you for porting crawl to Haiku. None of the devteam members have a haiku set up to easily test this on, so we would be unable to fix this should it break in the future.
> 
> That said, it appears to work based on your provided links and be the appropriate solution, so I'm happy to include it if you could update this PR to include Haiku specific build instructions in [INSTALL.md](https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md).

I decided to keep the docs in the data directory like the other platforms, as keeping them separate was too convoluted. With this change, the compilation steps of "Other Linux/Unix" will suffice to build this on Haiku.

**Comment by ebering** [comment]
Thanks for the patch! No one on the devteam runs Haiku, so if this breaks we'll need external help to fix it. How would you like to be listed in the CREDITS?

**Comment by Crestwave** [comment]
> Thanks for the patch! No one on the devteam runs Haiku, so if this breaks we'll need external help to fix it. 

No problem, this is expected. Haiku isn't exactly a mainstream OS so we typically hold the responsibility to maintain patches.

> How would you like to be listed in the CREDITS?

Justin Clark Ong

**Pull request merged**
