### PR TITLE
Fix a few obsolete references to MR (magic resistance).

### PR DESCRIPTION
**Pull request by pooka109**

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Seems reasonable, but do you mind fixing your commit messages to fit our [conventions](https://github.com/crawl/crawl/blob/master/crawl-ref/docs/develop/coding_conventions.md#1---commit-conventions)? I'll be happy to merge after that.

**Comment by pooka109** [comment]
Thank you. Is this better?

**Comment by PleasingFungus** [comment]
Yes, these are fine. Thank you! :)

(For future reference, I might have titled them something like "Fix name of ENCH_LOWERED_WL", "Fix name of _foe_mr_lower_goodness", and "Fix hex_success_chance prototype".)

**Comment by PleasingFungus** [comment]
Actually, looking at them again, these commit titles are 65 characters long, and we usually want those to be 50 characters or less. Otherwise, various bits of UI break. Not the end of the world, though. :)

**Pull request merged**
