### PR TITLE
Adding a variety of new arrival vaults

### PR DESCRIPTION
**Pull request by psywombats**
First time vault submission, edits/feedback welcome if anything looks nonstandard. I've been working on a Tiled (.tmx) utility to make generation a little more visual and am hoping to submit more vaults for other areas in the future.

### simple:
 - psy_arrival_basics - two exits and kite route
 - psy_arrival_conway - features a plant glider pattern
 - psy_arrival_dodecagon - floating star, can generate with 1 or 12 sides open to leave
 - psy_arrival_heroes - statue hall
 - psy_arrival_radial - two variable maps with radial symmetry
 - psy_arrival_whirlpool - shallow water paths

### small:
 - psy_arrival_batcave - a cave, with bats in it... batcave
 - psy_arrival_fountain - grove with a spring, half blocked off by plants
 - psy_arrival_solomon - variable map based on the seal of Solomon design, can generate as transparent or three separate rooms
 - psy_arrival_spokes - open 3-fork vault, some stuff in middle as it's vulnerable
 - psy_arrival_statuary - statues/fountains on a checkered floor design
 - psy_arrival_terrarium - some closed areas with water/plants

### large:
 - psy_arrival_wood_between_worlds - low-weight greenery vault with some id'd tele traps

### CODE REVIEW

**Comment by ebering** [comment]
These were put in a PR shortly before the 0.22 release, I'm sorry we didn't get to them then.

I'll try to review them this week.

At a cursory reading they look good. I'm a bit concerned that bat_cave places monsters. Some of our older arrival vaults do this, but it should be avoided for new vaults. If you think you can suggest the theme with bat corpses that could work, or you could add a small amount of loot and make it a regular early D vault.

**Comment by ebering** [comment]
I've merged some of these, with some tweaks. The tweaks were setting COLOUR (or removing COLOUR), and fixing up whitespace. When using custom tiles, it's nice to set colour to match.

Trailing whitespace is against crawl code style, this can be checked for and fixed automatically with util/checkwhite, something to use if you submit future vaults.

I did not merge the following vaults:
* psy_arrival_batcave As I said in my previous comment, we want to move away from arrival vault monsters.
* psy_arrival_solomon As a symbol this runs very close to the "no ascii art" rule. We have some more abstract symbols in the arrival vaults, but don't use ones with broader meaning.

Thanks for the submission!

**Comment by ebering** [comment]
P.S. How would you like to be listed in CREDITS.txt?

**Comment by psywombats** [comment]
@ebering Thanks for the feedback + merge, you patched things up before I could get home to remove the batty one haha

If arrival vaults merit credit mention then I wouldn't mind. Will hopefully be adding more soon. If there's a better channel to submit vaults just let me know. Thanks!

**Comment by ebering** [comment]
@psywombats Yes, it does merit credit mention. My question was what name would you like to be mentioned as?

PRs are a good avenue for vault submission, though it's helpful for them to each be in a separate commit, and we'll squash when merging into master.

**Pull request closed without merging**
