### PR TITLE
Updated documentation of use_animation

### PR DESCRIPTION
**Pull request by burnish3d**
Changed '-=' to '+=' to correctly describe default behavior.

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Hm, sort of unclear to me what the style here is. It might be trying to tell the user "here's how to set this", rather than defining "this is how this is set?" If so, telling the user to += something that's already included wouldn't be very useful.

What do you think?

**Comment by semitonal** [comment]
I'm not sure how closely it's kept to overall but the rule for options_guide is supposed to be that it lists the default setting, so I think technically the most consistent thing here would be to list it in the same way as `explore_stop` does (so `=` for initally setting the option, and then `+=` when it splits onto a second line).

**Comment by PleasingFungus** [comment]
Oh, https://www.reddit.com/r/dcss/comments/r52d2w/any_way_to_disable_boomerang_animation/hmn6upy/?utm_source=reddit&utm_medium=web2x&context=3 had more discussion of this (coming to the same conclusion as kate, I think?)

**Comment by burnish3d** [comment]
So would that be
use_animations = beam, range, hp, monster_in_sight, pickup, monster, player
use_animations += branch_entry
?

**Comment by burnish3d** [comment]
OK, so I took a look at the other three examples, fire_order_ability, use_animations, and monster_list_colour.  fire_order_ability and use_animations are both correct and were pointed out due to a misunderstanding, but I have updated monster_list_colour to be consistent (without touching the prose).

**Comment by burnish3d** [comment]
@semitonal Hey just wanted to ping you on this to get your attention again :)

**Comment by ebering** [comment]
Thanks for this! How would you like to appear in CREDITS.txt?

**Comment by burnish3d** [comment]
Put me down as Zachary Chandler. Neat!

**Pull request merged**
