### PR TITLE
Add doll editor info to docs/tiles_help.txt

### LINKED ISSUE #2815: docs/tiles_help.txt should mention the player doll editor
I haven't answered the usual questions since they don't seem germane, but I've just done a "git pull" on my vanilla source tree and docs/tiles_help.txt does not mention the player doll editor. I submit it should. The existence of the editor is otherwise relatively well-hidden.

### PR DESCRIPTION
**Pull request by michaelhunter27**
Adds a 'character appearance' section in tiles_help.txt that gives an overview of the Doll Editor.
Resolves #2815

### CODE REVIEW

**Comment by pooka109** [comment]
It's in. Thank you.

**Comment by pooka109** [comment]
Since this is your first contribution here, what name do you want to be listed under in the credits?

**Comment by michaelhunter27** [comment]
Michael Hunter

**Comment by pooka109** [comment]
Done. Thank you again.

**Pull request merged**
