### PR TITLE
new slime ending

### PR DESCRIPTION
**Pull request by yrdzrfxndfvh**
add a new slime ending in the shape of a (very rough) mandelbrot set
FEATURES:
- corrosive slime pillars in the main area
- azure jelly friends waiting for you in a pool
- potentially trapped entrance to trj area (can dig around it if its too scary)
- loot spindle

### CODE REVIEW

**Comment by PleasingFungus** [comment]
This is a very cool idea :)

**Comment by dillytin** [comment]
Are jellies able to activate net trap? If not, almost no point of putting a net trap at D

**Comment by regret-index** [comment]
The reason this vault doesn't fully build is that it needs to use "floor" and not "nothing".

I'd need to do pretty drastic redesign surgery to make this vault be good enough for 0.31's extremely impending feature freeze, and I'd discourage trying to push for that under the current circumstances. It's a pretty cute notion, but the layout is rather small compared to the current slime end set and has a very non-randomized component to TRJ's chamber being very full and also very small with only two real "sections" to a rather narrowed level. I'd rather reverse the positions of the stairs and TRJ (as fighting TRJ in the lower chamber would be far more variable between games), and would probably consider using two mandelbrots side-by-side pointed in opposite directions rather than the literalist approach of just placing a mandelbrot for the whole floor.

**Comment by yrdzrfxndfvh** [comment]
someone already made a mandelzot

**Pull request closed without merging**
