### PR TITLE
Stop monsters applying Flux enchant to each other (fix issue 3241)

### PR DESCRIPTION
**Pull request by NephilaWeaver**
It should now only apply if the player is the attacker. Even though it was really funny.

### CODE REVIEW

**Comment by NephilaWeaver** [comment]
*bounces excitedly*

**Comment by PleasingFungus** [comment]
BTW, are you in the credits already? And if not, how should we credit you?

**Comment by NephilaWeaver** [comment]
I'm not in the credits, no!  
I didn't know something like this would be enough for it, but it'd be an honor <3

**Comment by PleasingFungus** [comment]
We try to credit anyone who contributes any code. (But sometimes we forget.) Thanks again!

**Comment by NephilaWeaver** [comment]
Thanks a lot. This makes me happy. I'll try to contribute when I can!

**Pull request closed without merging**
