### PR TITLE
Fix manual typos

### PR DESCRIPTION
**Pull request by mwvdev**

### CODE REVIEW

**Comment by ebering** [comment]
Could you make the commit message more specific?

`Fix manual typos` would suffice.

**Comment by mwvdev** [comment]
@ebering Sure, I'll get right on that.

**Comment by mwvdev** [comment]
@ebering Alright, should be changed now.

**Comment by ebering** [comment]
Thanks for the patch!

**Comment by mwvdev** [comment]
You're welcome!

**Pull request merged**
