### PR TITLE
Address issue #0012378

### PR DESCRIPTION
**Pull request by dragonsploder**
This is my first time doing this, so this is just a very simple bug fix to get the feel of things.

### CODE REVIEW

**Comment by PleasingFungus** [comment]
Hey, thanks for submitting this! But I'm quite confused by this (both the PR and the bug report), sorry. Why do you think there is a bug here?

The goal of the recommended backgrounds/species lists isn't to list every single strong combination. It's to list a specific set of combinations that we think that players will enjoy. It's not a big deal to add brigand to this list, but I don't see any particular reason why we should. Could you please explain?

**Comment by dragonsploder** [comment]
Thanks for the quick reply. I don't have a great understanding of crawl balance, so I just assumed whoever made the bug report knew more than me. I guess we could add it because there are no other really "stealth" roles recommended for kobolds, and they have high aptitude in stealth, but I really don't know.

**Comment by PleasingFungus** [comment]
Gotcha!

To clarify, brigand isn't really a "stealth role" - they're a melee background that starts with some poison to deal with early tough enemies. And Stealth aptitudes aren't really very important - it's sometimes nice to be able to avoid fights, but if you're looking for a 'stealth playstyle', you need the ability to incapacitate enemies, with Stealth skill doesn't really help with.

For that reason, Enchanter actually is a 'stealth background' - it's the stealthiest background in the game. Arkane Marksperson also has some hexes, along with playing into kobolds' good ranged apts.

**Comment by dragonsploder** [comment]
Thanks. That makes sense. I can close the request, but I don't know how to deal with the bug report on the Mantis tracker.

**Comment by PleasingFungus** [comment]
Thanks, sorry for the confusion! I'll ask a Mantis admin to close your bug report.

**Pull request closed without merging**
