### PR TITLE
feat: Add menu_item_pad option

### PR DESCRIPTION
**Pull request by Antern**
Allows to disable padding in UI Menu for compact view.

### CODE REVIEW

**Comment by Antern** [comment]
Here is menu_items_pad = false
Screenshot 2023-02-28 at 03 35 07

**Comment by rawlins** [comment]
Good idea! Was this accidentally closed? Some suggestions based on reading the code:

* By convention, this option should have a name like `tiles_menu_item_pad` and be organized in the `3-n     Tiles Options.` section of the options guide (since it'll never make sense to have this option on console builds).
* As a boolean, I would rather give it a more intuitive name like `tiles_compact_menus` (with corresponding inverted semantics) -- the current name makes me think you could set the exact pad value. (Which would be a bit fine-grained to expose to the user.)
* If you haven't yet, it's worth testing this on various non-inventory menus and with other settings, especially `tile_menu_icons = false`
* Implementation: I think it might be simpler just to conditionally set `item_pad` to 0 instead of adding conditionals everywhere that `item_pad` is used, though maybe I'm missing some details that this would mess up.

**Comment by Antern** [comment]
@rawlins I've closed it, because it doesn't make much difference. 4 pixels per row in pretty specific conditions.
Thank you for the comments, I consider the tiles_compact_menus option with some addition tweaks, and will come back later with another PR if them will work.

**Comment by rawlins** [comment]
ah, got it. Yeah, on just testing removing the pad I do agree it's subtly noticeable but minor. I wonder if what you'd want to do for this idea is scale down the icons? I think people may already use `tile_menu_icons = false` as a defacto compact mode, so if you could get that spacing just by rendering the icons at half size, it might do what you're aiming for here.

**Pull request closed without merging**
